### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by jkbonfield** [tom-seddon/hackrom#2]
Not an issue at all, but just a thank you.

I discovered it by accident, but it's always pleasing to see something has (minimal!) value years later.

(James)

**Comment by tom-seddon** [comment]
Thanks James! I'd found the ROM handy when doing my BASIC Editor hacks a few years ago, and when writing tests for my emulator on real hardware. So when I found myself this year in the mood for some BBC Micro-related projects, I decided a minor update of the Hackers ROM would be one of them!

All the best,

--Tom
